#!/usr/bin/bash
# 
# John Selmys - January 2023
#
Usage () {
    echo 'Usage: allNarcissisticNumbers limit 
    displays all numbers from 1 to limit inclusive that are
narcissistic numbers!
A number is a narcissistic number if the sum of each of its individual digits
raised to the exponent of the total number of digits in the number equals
the value of the number itself, but excludes single digit numbers 0 to 9.
For each number that is determined to be a narcissistic number, it is displayed
as output followed by a new line.

So, for example, the number 153 is a narcissistic number because
1^3 + 5^3 + 3^3 = 153

For example, the number 1634 is a narcissistic number because
1^4 + 6^4 + 3^4 + 4^4 = 1634 '
}
if [ $# -ne 1 ];then
    Usage    
    exit
elif [[ ! $1 =~ ^[1-9][0-9]+$ ]];then
    Usage
    exit
else
    limit=$1
fi
for k in $(seq 10 $limit)
do
    l=${#k}
    t=0
    for j in $(seq 0 $((l-1)))
    do
        d=$((k/10**j%10))
        t=$((t+d**l))
    done
    if [ $t -eq $k ];then
        echo $t
    fi
done
