#!/bin/bash
#convert c to f temp
if (( $# == 1))
then
	c=$1
else
	read -p "enter c :" c
fi
if (( $# > 1 ))
then
	echo error
	exit 1
fi
if [[ ! $c =~ ^[\+\-]?[0-9]+\.?[0-9]*$ ]]
then
	echo  input error
	exit 2
fi
c=$(echo $c | tr -d '+')
result=$(echo "$c<-40 || $c>40" | bc)
if ((result == 1))
#if (( c < -40 || c > 40 ))
then
	echo $c must be between -40 and +40
	exit 3
fi
# finally convert c to f
f=$(echo "scale=3;$c*9.0/5.0+ 32.0" | bc)
echo $c celcius is $f fahrenheit
