#!/bin/bash
# Written by John Selmys - February 2012
# Updated - January 2014
# Seneca College, Toronto
#
# BASH script to print strings in colour
#
# Note: This script takes at least two parameters
#	    COLOUR - which will be the colour of the string (see code below)
#	    STRING - string to colourize
#
# Usage: echoc COLOUR STRING
#

declare -A colours=(
[black]="0;30" [red]="0;31" [green]="0;32" [yellow]="0;33" [blue]="0;34" [magenta]="0;35" [cyan]="0;36" [white]="0;37"
[BLACK]="1;30" [RED]="1;31" [GREEN]="1;32" [YELLOW]="1;33" [BLUE]="1;34" [MAGENTA]="1;35" [CYAN]="1;36" [WHITE]="1;37")

if [ $# -lt 2 ]; then
	echo Usage: echoc COLOUR STRING
	exit 1
fi

regex='^black$|^red$|^green$|^yellow$|^blue$|^magenta$|^cyan$|^white$'
shopt -s nocasematch

if [[ $1 =~ $regex ]]; then
	echo -ne '\e['${colours[$1]}m
	shift
	echo -e $*'\e[0m'
	exit 0
else
	echo COLOUR must be one of 'black|red|green|yellow|blue|magenta|cyan|white'
	echo or 'BLACK|RED|GREEN|YELLOW|BLUE|MAGENTA|CYAN|WHITE' for bold 
	exit 2
fi


