#!/usr/bin/bash
# by John Selmys - Sept 2023 - Nov 2023
if [ $# -eq 0 ]
then
    echo "Usage: ./exp2float e1 e2 ..."
    echo "where e1, e2, ... are numbers using"
    echo "scientific (engineering) notation"
    echo "for example: 2.123e-2"
    echo "NOTE: one digit before the decimal"
    echo "      use 'e' or 'E'"
    exit
fi
for n in $*
do
    res=$(echo $n | egrep '^(-[0-9]|[0-9])\.[0-9]+[eE][-+][0-9]+$')
    if [ "$res" != "" ]
    then
        n=$(echo $n | tr 'E' 'e')
        m=$(echo $n | cut -de -f1)
        e=$(echo $n | cut -de -f2)
        expsign=$(echo $e | cut -c1)
        count=$(echo $e | cut -c2-)
        # remove leading zero from exponent
        res=$(echo $count | grep '^0')
        if [ "$res" != "" ]
        then
            count=$(echo $count | cut -c2-)
        fi
        p=$((10**count))
        scale=${#m}
        if [ $expsign == \- ]
        then
            scale=$((scale+count-2))
            r=$(echo "scale=$scale;$m / $p" | bc)
        else
            scale=$((scale-count-2))
            r=$(echo "scale=$scale;$m * $p" | bc)
        fi
        printf '%.'$scale'f\n' $r
    else
        echo Invalid Input $n
    fi
done
