#!/bin/bash
# convert inches to centimeters 
if (( $# == 1)) #check for 1 command line parameter
then
	inches=$1
else
	read -p "How many inches? " inches
fi
# check if user input is numeric
if [[ ! $inches =~ ^\+?[0-9]+\.?[0-9]*$ ]]
then
	echo $inches is not a number
	exit 3
fi
inches=$(echo $inches | tr -d '+')
#cm=$((254*inches/100))
cm=$(echo "$inches*2.54" | bc)
echo $inches inches is $cm centimeters
