#!/bin/bash
#
# generate Canadian postal codes
# John Selmys - 2022
#
if [ $# -ne 1 ];then
    echo Usage: ./pc number_of_postal_codes
    exit
fi
n=$1
for ((i=0;i<n;i++))
do
    L1=$(echo 'ABCEGHJKLMNPRSTVXY' | cut -c$((RANDOM%18+1)))
    D1=$(echo '0123456789' | cut -c$((RANDOM%10+1)))
    L2=$(echo 'ABCEGHJKLMNPRSTVWXYZ' | cut -c$((RANDOM%20+1)))
    D2=$(echo '0123456789' | cut -c$((RANDOM%10+1)))
    L3=$(echo 'ABCEGHJKLMNPRSTVWXYZ' | cut -c$((RANDOM%20+1)))
    D3=$(echo '0123456789' | cut -c$((RANDOM%10+1)))
    echo $L1$D1$L2 $D2$L3$D3
done
