#!/bin/bash
# Move first line to end of file
# John Selmys - 2022
if [ $# -eq 1 ]
then
    file=$1
    count=1
else
    if [ $# -eq 2 ]
    then
        file=$1
        count=$2
    else
        echo Usage: ./rotate file [count]
        echo where count is 1 if not given
        exit
    fi
fi
cp $file /tmp/$USER$file
for ((i=0;i<count;i++))
do
    head -1 /tmp/$USER$file >> /tmp/$USER$file
    sed -i '1d' /tmp/$USER$file
done
cat /tmp/$USER$file
rm /tmp/$USER$file
