#!/bin/bash
# John Selmys - July 22, 2022
#
if [ $# != 1 ];then
    echo Usage: ./sinewave n
    echo where n = number of cycles
    exit
fi
n=$1
y=0
for ((i=0;i<n;i++))
do
    for ((d=0;d<360;d+=5))
    do
        a=$(echo "scale=5;s($d*3.14159/180.0)"|bc -l)
        m=$(tput cols)
        m=$((m/2))
        x=$(echo "$m+$m*$a"|bc)
        x1=$(echo $x | sed 's/\.[0-9]*$//')
        tput cup $y $x1
        ((y++))
        echo '*'
        sleep 0.1
    done
done
